/* PS5 OpenGL - OpenGL implementation for PlayStation 5.
 * Copyright (C) 2026 BlackBearReloaded
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

GROUP (
  libps5_opengl_core33.a
  libglapi_bridge.a
  libpsbc.ps5.a
  libmesa.a
  libmesa_sse41.a
  libgallium.a
  libglapi.a
  libglsl.a
  libglcpp.a
  libglsl_util.a
  libvtn.a
  libnir.a
  libcompiler.a
  libmesa_util.a
  libmesa_util_simd.a
  libblake3.a
  libmesa_util_c11.a
)
